config/routes.rb
Wellness::Application.routes.draw do

  resources :home do
    collection do
      get 'patient'
      get 'fitness'
      get 'diet'
      get 'medication'
      get 'risks'
      get 'targets'
      get 'calendar'
      get 'stats'
      get 'dashboard'
      get 'weight_bmi'
      get 'flot_charts'
    end
  end

  get '/patient/:id' => 'home#patient'

  get '/demo' => 'home#demo', as: 'demo'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signup',  to: 'users#new',            via: 'get'

  root 'home#index'
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :email_confirmation
	attr_accessor :add1
	attr_accessor :add2
	attr_accessor :add3
	attr_accessor :phone1
	attr_accessor :phone2
	attr_accessor :phone3
	attr_accessor :firstname
	attr_accessor :lastname
 
    before_save { if (self.id == nil) then self.email = email.downcase; self.hospitaladdress = add1  + "," + add2 + "," + add3; self.phone = phone1 + phone2 + phone3; self.name = firstname + " " + lastname; end}
  	before_create :create_remember_token
	validates :firstname, presence: true, length: { maximum: 25 }
	validates :lastname, presence: true, length: { maximum: 25 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
	uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: { minimum: 6 }
	validate :check_email
	

	def check_email
	  errors.add(:email, "addresses are different!") if email.downcase != email_confirmation.downcase
	end
	
	def check_phone
	  errors.add(:phone, "number is Incorrect!") if (!(/\A\d+\z/ === phone))
	end
	
	def User.new_remember_token
      SecureRandom.urlsafe_base64
    end

    def User.hash(token)
      Digest::SHA1.hexdigest(token.to_s)
    end

    private

		def create_remember_token
		  self.remember_token = User.hash(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'session'
  def new
  end

  def create
	 user = User.find_by(email: params[:session][:email].downcase)
	  if user && user.authenticate(params[:session][:password])
	    rememberMe = params[:session][:remember_me]
	    sign_in user
		redirect_to user
	  else
		flash.now[:error] = 'Invalid email/password combination' # Not quite right!
        render 'new'
	  end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'user'
  def new
  @user = User.new
  end
  def show
    #@user = User.find(params[:id]) 
	redirect_to "/patient/1"
  end
   def create
    @user = User.new(user_params)
    if @user.save
	  sign_in @user
	  redirect_to "/patient/1"
      #redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

  private

    def user_params
	  params.require(:user).permit(:email, :email_confirmation, :password, 
                                  :password_confirmation, :firstname,:lastname, :hospitalname, :add1, :add2, :add3,
								  :phone1, :phone2, :phone3)	
      								  
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
	user.update_attribute(:remember_token, User.hash(remember_token))
	self.current_user = user
  end
  def signed_in?
    !current_user.nil?
  end
  def current_user=(user)
    @current_user = user
  end
  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  def rememberMe=(flag)
    @rememberMe = flag
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
	 #image_tag(gravatar_url, alt: user.name, class: "gravatar")
    image_tag(gravatar_url, alt: user.firstname, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<div class="container">
<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".sidebar-nav.nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="/"> <img alt="Perfectum Dashboard" src="/assets/wellness_logo_trans.png"/>
  <!--<span>Wellness</span>-->
</a>

<span style="margin: 5px;">
  <%= text_field_tag 'search', nil, placeholder: 'Search by patient name', class: 'form-control patient-search', style: 'display: inline; ' %>
</span>

<div class="header-nav">
<ul class="nav navbar-nav pull-right nav-people">
  <li class="dropdown hidden-xs">
    <a class="btn" href="#">
      <i class="fa fa-group"></i>
    </a>
  </li>

  <li class="dropdown hidden-xs">
    <a class="btn" href="#">
      <i class="fa fa-comments"></i>
    </a>
  </li>

  <li class="dropdown hidden-xs">
    <a class="btn" href="#">
      <i class="fa fa-globe"></i>
    </a>
  </li>

</ul>
</div>
<!-- end: Header Menu -->

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Wellness</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- start: Meta -->
  <meta charset="utf-8">
  <title>Wellness</title>
  <meta name="description" content="--Wellness--">
  <meta name="author" content="Duke">

  <link href='http://fonts.googleapis.com/css?family=Lato:400,700,900,300italic,400italic,700italic' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--<script src="/assets/jquery.js"></script>-->
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>



  <!--[if lt IE 9 ]>
    <link href="assets/style-ie.css" rel="stylesheet">
  <![endif]-->

  <!-- end: CSS -->


  <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>

  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <script src="assets/respond.min.js"></script>

  <![endif]-->
</head>
<body style="">

<!-- start: Header -->
<div class="navbar">
  <%= render partial: '/layouts/header' %>
</div>
<!-- start: Header -->

<div class="container">
  <div class="row">
  <%= yield %>
  </div>


  <!-- /.modal -->

  <div class="clearfix"></div>


  <footer>
    <p>
      <span style="text-align:left;float:left">&copy; 2013 Wellness</span>
    </p>
  </footer>

</div>

<!-- start: JavaScript-->
<!--[if !IE]>-->

<!--<script src="/assets/jquery-2.0.3.min.js"></script>-->

<!--<![endif]-->

<!--[if IE]>

<!--<script src="assets/jquery-1.10.2.min.js"></script>-->

<![endif]-->

<!--[if !IE]>-->

<script type="text/javascript">
  window.jQuery || document.write("<script src='assets/jquery-2.0.3.min.js'>" + "<" + "/script>");
</script>

<!--<![endif]-->

<!--[if IE]>

<script type="text/javascript">
  window.jQuery || document.write("<script src='assets/jquery-1.10.2.min.js'>" + "<" + "/script>");
</script>

<![endif]-->

<%= javascript_tag do %>
  var params = <%= raw params.to_json %>;
<% end %>

</body>
</html>

<script type="text/javascript">
$('#content').prepend("<div class='row' id='loading' style='text-align: center'><img alt='Ajax loader' src='/assets/ajax-loader.gif'></div>")
</script>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Wellness Sign in</title>
	<link rel="stylesheet" type="text/css" href="/assets/session.css" />
    <%# stylesheet_link_tag "sessions", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "sessions", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
	 <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
     <% end %>
	 <div>
		<%= image_tag asset_path("portal.png") %>
		<br>
		<br>
			<div class="col-md-4 col-md-offset-4">
			<%= form_for(:session, url: sessions_path) do |f| %>
			<div><%= f.text_field :email, placeholder: '  email address' %></div>
			<div><%= f.password_field :password, placeholder: '  password' %></div> 
			<label>
            <%= f.check_box :remember_me %> remember me
			</label>
 			<div><%= f.submit "SIGN IN", class:'submit_button'%></div>
			<% end -%>
			<p>new to wellness? <%= link_to "create an account",  signup_path, style: 'color:#99FF66' %></p></div>
		</div>
	</div>
  </div>
</body>
</html>



app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wellness - Sign up</title>
	<link rel="stylesheet" type="text/css" href="/assets/session.css" />
    <%# stylesheet_link_tag "sessions", "data-turbolinks-track" => true %>
    <%# javascript_include_tag "sessions", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
	<div class="container">
	    <% flash.each do |key, value| %>
           <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
	    <div class="row">
	       <%= image_tag asset_path("signup.png") %>
        <%= form_for(@user) do |f| %>
	  <%= render 'shared/error_messages' %>
	  <div class="col-md-4 col-md-offset-1" style="margin-bottom: 20px;">
	      <p class="p_title">  Account information </p>
	  	  <div> <%= f.text_field :email, style: 'width:300px', placeholder: ' email address' %></div>
		  <div> <%= f.text_field :email_confirmation, style: 'width:300px', placeholder: ' confirm email address' %></div>
		  <div> <%= f.password_field :password, style: 'width:300px', placeholder: ' password' %></div>
		  <div> <%= f.password_field :password_confirmation, style: 'width:300px', placeholder: ' confirm password' %></div>
	  </div>
	  <hr  noshade size=7 width=800px>
      <div class="col-md-4 col-md-offset-1">
	     <p class="p_title">  Profile information </p>	  
		 <upload>
			<img alt="wellness" src="/assets/user.png"/>
		 </upload>
		 <upload>
			<button type="button">UPLOAD PHOTO</button>
		 </upload>
		 <div style="margin-top: 30px;">
		 <%= f.text_field :firstname,   style: 'width:200px', placeholder: ' first name' %> 
	     <%= f.text_field :lastname,  style: 'width:200px', placeholder: ' last name'  %> 
		 </div>
		 <%= f.text_field :hospitalname,   style: 'width:300px', placeholder: ' hospital/clinic name' %>
		 <div>
		  <%= f.text_field :add1, style: 'width:400px', placeholder: ' hospital/clinic address' %>
		  <%= f.text_field :add2, style: 'width:45px', placeholder: 'state' %>
		  <%= f.text_field :add3, style: 'width:65px',  placeholder: ' zipcode' %>
		 </div>
		 <p class="p_title">  phone </p>	  
		 <div>
		  <%= f.text_field :phone1, style: 'width:45px' %>
		  <%= f.text_field :phone2, style: 'width:45px' %>
		  <%= f.text_field :phone3, style: 'width:60px' %>
		 </div>
		 <%= f.submit "CREATE ACCOUNT", class:'submit_button', style: 'width:300px'%>
	</div> 
    <% end %>
	</div>
    </div>
  </body>
</html>